# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import pathlib
import re
import subprocess
import sys

import pytest

pytestmark = pytest.mark.skipif(
    sys.platform.startswith('win'), reason='POSIX shell script.'
)

_SCRIPT = (
    pathlib.Path(__file__).resolve().parents[3]
    / 'scripts'
    / 'update_constraints.sh'
)
_PYTHON_VERSIONS = ('3.10', '3.11', '3.12', '3.13', '3.14')
# The version whose header the malformed-header tests corrupt; the other four
# stay well-formed so the tests can also assert per-file failure isolation.
_BROKEN_VERSION = '3.12'
_SNAPSHOT_DATE = '2026-01-02'
_PINNED_PACKAGE = 'typing-extensions==4.12.2'
_NO_SNAPSHOT_DATE_MESSAGE = (
    "has no single '--exclude-newer YYYY-MM-DD' snapshot date in its header,"
)
# A stub `uv` that records its argv and writes the file named by `-o` instead
# of resolving against PyPI, so the success path can be exercised without
# network access. The script keeps only `tail -n +3` of the output it writes,
# hence the two header lines.
_UV_STUB = """#!/bin/bash
printf '%s\\n' "$*" >> "{call_log}"
while [ "$#" -gt 0 ]; do
  if [ "$1" = "-o" ]; then
    printf '# header\\n# command\\n{pinned_package}\\n' > "$2"
    exit 0
  fi
  shift
done
exit 1
"""


def _install_uv_stub(tmp_path: pathlib.Path) -> tuple[str, pathlib.Path]:
  """Installs the stub `uv`, returning the PATH to run with and its call log."""
  stub_dir = tmp_path / 'bin'
  stub_dir.mkdir()
  call_log = tmp_path / 'uv-calls.log'
  stub = stub_dir / 'uv'
  stub.write_text(
      _UV_STUB.format(call_log=call_log, pinned_package=_PINNED_PACKAGE)
  )
  stub.chmod(0o755)
  return f'{stub_dir}:/usr/bin:/bin', call_log


def _uv_calls(call_log: pathlib.Path) -> list[str]:
  """Returns the argv of each `uv` invocation the script made, in order."""
  return call_log.read_text().splitlines() if call_log.exists() else []


def _generated_file(version: str, date: str = _SNAPSHOT_DATE) -> str:
  """Returns constraints content byte-identical to what the script rebuilds.

  A fixture written from this compares equal to the regenerated candidate, so
  check mode reports it as up-to-date.
  """
  return (
      '# This file was autogenerated by uv via the following command:\n'
      '#    uv pip compile pyproject.toml --all-extras --python-version'
      f' {version} --exclude-newer {date} --index-url'
      f' https://pypi.org/simple -o constraints-{version}.txt\n'
      f'{_PINNED_PACKAGE}\n'
  )


def _write_constraints(tmp_path: pathlib.Path) -> None:
  """Writes a well-formed, up-to-date constraints file for every version."""
  for version in _PYTHON_VERSIONS:
    (tmp_path / f'constraints-{version}.txt').write_text(
        _generated_file(version)
    )


def _run(
    tmp_path: pathlib.Path, path: str, *args: str
) -> subprocess.CompletedProcess[str]:
  """Runs the script in an isolated CWD with an explicit PATH and HOME.

  Setting HOME is mandatory: the script prepends `$HOME/.local/bin` to PATH,
  so leaving the developer's real HOME in place would let a real `uv` shadow
  the stub and make the missing-`uv` test pass for the wrong reason.
  """
  (tmp_path / 'pyproject.toml').write_text(
      '[project]\nname = "x"\nversion = "0.1"\n'
  )
  return subprocess.run(
      ['bash', str(_SCRIPT), *args],
      cwd=tmp_path,
      env={'PATH': path, 'HOME': str(tmp_path)},
      capture_output=True,
      text=True,
      check=False,
  )


def test_fails_fast_with_actionable_message_when_uv_missing(
    tmp_path: pathlib.Path,
) -> None:
  result = _run(tmp_path, '/usr/bin:/bin')

  output = result.stdout + result.stderr
  assert result.returncode == 1
  assert 'uv was not found on PATH' in output
  assert 'https://docs.astral.sh/uv/getting-started/installation/' in output
  # The pre-existing failure mode: a missing tool was reported as a phantom
  # dependency conflict, sending readers off to debug the wrong problem.
  assert 'Resolution failed' not in output
  assert not list(tmp_path.glob('constraints-*.txt'))


def test_regenerates_constraints_when_uv_available(
    tmp_path: pathlib.Path,
) -> None:
  path, _ = _install_uv_stub(tmp_path)

  result = _run(tmp_path, path)

  output = result.stdout + result.stderr
  assert 'uv was not found on PATH' not in output
  for version in _PYTHON_VERSIONS:
    assert (tmp_path / f'constraints-{version}.txt').exists()
  # The script is a fixer, not a check: it rewrites missing or stale targets
  # and exits non-zero whenever it wrote. That is why it cannot serve as a CI
  # gate, and why the hook belongs on the `manual` stage.
  assert result.returncode == 1


@pytest.mark.parametrize(
    'malformed',
    [
        pytest.param(
            _generated_file(_BROKEN_VERSION).replace(
                f' --exclude-newer {_SNAPSHOT_DATE}', ''
            ),
            id='snapshot-flag-absent',
        ),
        pytest.param('', id='file-empty'),
        pytest.param(
            _generated_file(_BROKEN_VERSION, '2026-7-1'),
            id='date-not-zero-padded',
        ),
        # Two headers -- e.g. two files concatenated -- record two dates, and
        # neither one can be assumed to be the snapshot the pins came from.
        pytest.param(
            _generated_file(_BROKEN_VERSION)
            + _generated_file(_BROKEN_VERSION, '2026-03-04'),
            id='two-recorded-dates',
        ),
    ],
)
def test_check_mode_rejects_a_header_without_a_readable_snapshot_date(
    tmp_path: pathlib.Path, malformed: str
) -> None:
  path, call_log = _install_uv_stub(tmp_path)
  _write_constraints(tmp_path)
  target = tmp_path / f'constraints-{_BROKEN_VERSION}.txt'
  target.write_text(malformed)

  result = _run(tmp_path, path, '--check')

  assert result.returncode == 1
  assert (
      f'constraints-{_BROKEN_VERSION}.txt {_NO_SNAPSHOT_DATE_MESSAGE}'
      in result.stdout
  )
  # The file is not stale, so it must not be reported as such.
  assert (
      f'constraints-{_BROKEN_VERSION}.txt is OUT OF DATE' not in result.stdout
  )
  calls = _uv_calls(call_log)
  # The fix itself: no resolution is attempted for that file, so check mode
  # can never fall back to verifying the pins against the live index.
  assert not [call for call in calls if _BROKEN_VERSION in call]
  assert target.read_text() == malformed
  # Failures are isolated: the remaining versions are still checked.
  assert len(calls) == len(_PYTHON_VERSIONS) - 1
  for version in _PYTHON_VERSIONS:
    if version != _BROKEN_VERSION:
      assert f'✅ constraints-{version}.txt is up-to-date.' in result.stdout


def test_check_mode_resolves_against_the_recorded_snapshot_date(
    tmp_path: pathlib.Path,
) -> None:
  path, call_log = _install_uv_stub(tmp_path)
  _write_constraints(tmp_path)

  result = _run(tmp_path, path, '--check')

  assert result.returncode == 0
  calls = _uv_calls(call_log)
  assert len(calls) == len(_PYTHON_VERSIONS)
  for call in calls:
    assert f'--exclude-newer {_SNAPSHOT_DATE}' in call


def test_check_mode_reports_missing_files_without_resolving(
    tmp_path: pathlib.Path,
) -> None:
  path, call_log = _install_uv_stub(tmp_path)

  result = _run(tmp_path, path, '--check')

  assert result.returncode == 1
  for version in _PYTHON_VERSIONS:
    assert f'❌ constraints-{version}.txt is missing!' in result.stdout
  assert _NO_SNAPSHOT_DATE_MESSAGE not in result.stdout
  assert not _uv_calls(call_log)


def test_update_mode_regenerates_a_file_with_a_malformed_header(
    tmp_path: pathlib.Path,
) -> None:
  path, call_log = _install_uv_stub(tmp_path)
  target = tmp_path / f'constraints-{_BROKEN_VERSION}.txt'
  target.write_text(
      _generated_file(_BROKEN_VERSION).replace(
          f' --exclude-newer {_SNAPSHOT_DATE}', ''
      )
  )

  result = _run(tmp_path, path)

  # Update mode owns the snapshot date, so a malformed header is something it
  # repairs rather than something it refuses to read.
  assert _NO_SNAPSHOT_DATE_MESSAGE not in result.stdout
  assert (
      f'🔄 constraints-{_BROKEN_VERSION}.txt was OUT OF DATE. Updating it'
      ' automatically...'
      in result.stdout
  )
  broken_calls = [
      call for call in _uv_calls(call_log) if _BROKEN_VERSION in call
  ]
  assert len(broken_calls) == 1
  # The date is `today - 4 days`; assert the shape only, to avoid a race with
  # a midnight rollover between the script's clock and the test's.
  recorded = re.search(r'--exclude-newer (\d{4}-\d{2}-\d{2}) ', broken_calls[0])
  assert recorded is not None
  assert target.read_text() == _generated_file(
      _BROKEN_VERSION, recorded.group(1)
  )
