# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import annotations

from collections.abc import Sequence
import io
import pathlib
import subprocess
import sys

import pytest

from scripts import strip_constraint_provenance

_CONSTRAINT = 'constraints-3.10.txt.stable.tmp'
_DROPPED = f'    #   -c {_CONSTRAINT}'
_VIA_HEADER = '    # via'
_SOURCE_INDENT = '    #   '

_HELPER_PATH = str(pathlib.Path(strip_constraint_provenance.__file__).resolve())
_REPO_ROOT = pathlib.Path(_HELPER_PATH).parents[1]
_CONSTRAINTS_FILES = sorted(_REPO_ROOT.glob('constraints-*.txt'))


def _find_malformed_via_blocks(lines: Sequence[str]) -> list[str]:
  """Finds every `# via` block that uv would not have written.

  uv lists a single source on the `# via` line itself, so a bare `# via`
  header must be followed by two or more indented sources. Zero sources also
  means the pin records no reason at all.

  Args:
    lines: The lines of a constraints file, without line endings.

  Returns:
    One description per malformed block, empty when the file is canonical.
  """
  problems: list[str] = []
  for index, line in enumerate(lines):
    if line != _VIA_HEADER:
      continue
    sources = 0
    for following in lines[index + 1 :]:
      if not following.startswith(_SOURCE_INDENT):
        break
      sources += 1
    if sources < 2:
      problems.append(f'line {index + 1}: `# via` header lists {sources}')
  return problems


def test_collapses_block_to_a_single_source() -> None:
  lines = [
      'a2a-sdk==1.1.1',
      _VIA_HEADER,
      _DROPPED,
      '    #   google-adk (pyproject.toml)',
  ]
  assert strip_constraint_provenance.strip_provenance(lines, _CONSTRAINT) == [
      'a2a-sdk==1.1.1',
      '    # via google-adk (pyproject.toml)',
  ]


def test_keeps_the_block_form_when_several_sources_remain() -> None:
  lines = [
      'defusedxml==0.7.1',
      _VIA_HEADER,
      _DROPPED,
      '    #   llama-index-readers-file',
      '    #   nltk',
  ]
  assert strip_constraint_provenance.strip_provenance(lines, _CONSTRAINT) == [
      'defusedxml==0.7.1',
      _VIA_HEADER,
      '    #   llama-index-readers-file',
      '    #   nltk',
  ]


def test_drops_the_via_header_when_no_source_remains() -> None:
  lines = ['orphan==1.0.0', _VIA_HEADER, _DROPPED]
  assert strip_constraint_provenance.strip_provenance(lines, _CONSTRAINT) == [
      'orphan==1.0.0'
  ]


def test_drops_the_inline_via_form() -> None:
  lines = ['orphan==1.0.0', f'{_VIA_HEADER} -c {_CONSTRAINT}', 'next==2.0.0']
  assert strip_constraint_provenance.strip_provenance(lines, _CONSTRAINT) == [
      'orphan==1.0.0',
      'next==2.0.0',
  ]


def test_keeps_a_different_constraint_file() -> None:
  lines = [
      'requests==2.32.3',
      _VIA_HEADER,
      '    #   -c some-other.txt',
      f'    #   -c {_CONSTRAINT}.bak',
      '    #   probe (pyproject.toml)',
      'urllib3==2.2.3',
      f'{_VIA_HEADER} -c some-other.txt',
  ]
  assert (
      strip_constraint_provenance.strip_provenance(lines, _CONSTRAINT) == lines
  )


def test_preserves_pins_headers_and_unrecognized_comments() -> None:
  lines = [
      '# This file was autogenerated by uv via the following command:',
      '#    uv pip compile pyproject.toml --all-extras',
      '    #   a stray source line outside any block',
      'anyio==4.14.2',
      _VIA_HEADER,
      _DROPPED,
      '    #   anthropic',
      '    #   starlette',
      'attrs==26.1.0',
      '    # via aiohttp',
  ]
  assert strip_constraint_provenance.strip_provenance(lines, _CONSTRAINT) == [
      '# This file was autogenerated by uv via the following command:',
      '#    uv pip compile pyproject.toml --all-extras',
      '    #   a stray source line outside any block',
      'anyio==4.14.2',
      _VIA_HEADER,
      '    #   anthropic',
      '    #   starlette',
      'attrs==26.1.0',
      '    # via aiohttp',
  ]


def test_is_idempotent() -> None:
  lines = [
      'a2a-sdk==1.1.1',
      _VIA_HEADER,
      _DROPPED,
      '    #   google-adk (pyproject.toml)',
      'defusedxml==0.7.1',
      _VIA_HEADER,
      _DROPPED,
      '    #   llama-index-readers-file',
      '    #   nltk',
  ]
  once = strip_constraint_provenance.strip_provenance(lines, _CONSTRAINT)
  assert strip_constraint_provenance.strip_provenance(once, _CONSTRAINT) == once


def test_main_reads_stdin_and_writes_stdout(
    monkeypatch: pytest.MonkeyPatch, capsys: pytest.CaptureFixture[str]
) -> None:
  stdin = io.StringIO(
      f'a2a-sdk==1.1.1\n{_VIA_HEADER}\n{_DROPPED}\n    #   google-adk\n'
  )
  monkeypatch.setattr(strip_constraint_provenance.sys, 'stdin', stdin)

  assert (
      strip_constraint_provenance.main(['--constraint-file', _CONSTRAINT]) == 0
  )
  assert capsys.readouterr().out == 'a2a-sdk==1.1.1\n    # via google-adk\n'


def test_main_rejects_a_missing_constraint_file_flag() -> None:
  with pytest.raises(SystemExit):
    strip_constraint_provenance.main([])


def test_running_the_helper_as_a_subprocess_filters_stdin() -> None:
  """Exercises the invocation `update_constraints.sh` actually performs."""
  result = subprocess.run(
      [sys.executable, _HELPER_PATH, '--constraint-file', _CONSTRAINT],
      input=f'a2a-sdk==1.1.1\n{_VIA_HEADER}\n{_DROPPED}\n    #   google-adk\n',
      capture_output=True,
      text=True,
      check=True,
  )
  assert result.stdout == 'a2a-sdk==1.1.1\n    # via google-adk\n'


def test_the_helper_exits_non_zero_without_a_constraint_file() -> None:
  """Proves a misuse aborts the `set -o pipefail` shell pipeline."""
  result = subprocess.run(
      [sys.executable, _HELPER_PATH],
      input='',
      capture_output=True,
      text=True,
      check=False,
  )
  assert result.returncode != 0
  assert '--constraint-file' in result.stderr


def test_the_repository_ships_constraints_files() -> None:
  assert _CONSTRAINTS_FILES, f'no constraints-*.txt found under {_REPO_ROOT}'


@pytest.mark.parametrize('path', _CONSTRAINTS_FILES, ids=lambda p: p.name)
def test_no_committed_file_names_a_temporary_constraint(
    path: pathlib.Path,
) -> None:
  assert '.stable.tmp' not in path.read_text(encoding='utf-8')


@pytest.mark.parametrize('path', _CONSTRAINTS_FILES, ids=lambda p: p.name)
def test_every_via_block_is_canonical(path: pathlib.Path) -> None:
  lines = path.read_text(encoding='utf-8').splitlines()
  assert _find_malformed_via_blocks(lines) == []


def test_the_block_checker_reports_a_malformed_block() -> None:
  lines = [
      'orphan==1.0.0',
      _VIA_HEADER,
      'uncollapsed==2.0.0',
      _VIA_HEADER,
      '    #   only-one',
      'canonical==3.0.0',
      _VIA_HEADER,
      '    #   first',
      '    #   second',
  ]
  assert _find_malformed_via_blocks(lines) == [
      'line 2: `# via` header lists 0',
      'line 4: `# via` header lists 1',
  ]
