# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tests for the ``scripts/update_constraints.sh`` command line contract.

The script resolves `constraints-<ver>.txt` against a PyPI snapshot a few days
old, so the snapshot date is part of the artifact and is read back out of the
file header. These tests pin the three properties that make the artifacts
usable by automation:

* The recorded snapshot date is reused in every mode, so a run on a later day
  is not reported as drift. `--refresh` is the one way to advance it.
* An unrecognised flag is a usage error. A typo such as `--chek` used to fall
  through to update mode, which turns the CI check job into a job that
  rewrites the files and verifies nothing.
* A successful update exits 0, so a caller can tell a rewrite from a failure.

The script is driven as a subprocess against a stub `uv`, so no test reaches
PyPI.
"""

from __future__ import annotations

import datetime
import pathlib
import subprocess
import sys

import pytest

pytestmark = pytest.mark.skipif(
    sys.platform.startswith('win'), reason='POSIX shell script.'
)

_SCRIPT = (
    pathlib.Path(__file__).resolve().parents[3]
    / 'scripts'
    / 'update_constraints.sh'
)
_PYTHON_VERSIONS = ('3.10', '3.11', '3.12', '3.13', '3.14')
_PIN = 'typing-extensions==4.12.2'
_OLD_DATE = '2020-01-01'

# A stub `uv` that appends its argv to a log and writes the file named by `-o`
# instead of resolving against PyPI. The script keeps only `tail -n +3` of that
# output, hence the two throwaway header lines.
_UV_STUB = """#!/bin/bash
printf '%s\\n' "$*" >> "{call_log}"
while [ "$#" -gt 0 ]; do
  if [ "$1" = "-o" ]; then
    printf '# header\\n# command\\n{pin}\\n' > "$2"
    exit 0
  fi
  shift
done
exit 1
"""


def _four_days_ago() -> str:
  """Returns the snapshot date the script computes for a fresh file."""
  return str(datetime.date.today() - datetime.timedelta(days=4))


def _generated(version: str, date: str, pin: str = _PIN) -> str:
  """Returns the exact bytes the script writes for ``version`` and ``date``."""
  return (
      '# This file was autogenerated by uv via the following command:\n'
      '#    uv pip compile pyproject.toml --all-extras --python-version'
      f' {version} --exclude-newer {date} --index-url'
      f' https://pypi.org/simple -o constraints-{version}.txt\n'
      f'{pin}\n'
  )


def _write_all(tmp_path: pathlib.Path, date: str) -> None:
  """Writes an up-to-date constraints file for every supported version."""
  for version in _PYTHON_VERSIONS:
    (tmp_path / f'constraints-{version}.txt').write_text(
        _generated(version, date)
    )


def _constraints(tmp_path: pathlib.Path, version: str) -> pathlib.Path:
  return tmp_path / f'constraints-{version}.txt'


class _Run:
  """The outcome of one script invocation."""

  def __init__(
      self, process: subprocess.CompletedProcess[str], call_log: pathlib.Path
  ) -> None:
    self.returncode = process.returncode
    self.stdout = process.stdout
    self.stderr = process.stderr
    self.uv_calls = (
        call_log.read_text().splitlines() if call_log.exists() else []
    )


def _resolved_with(result: _Run, version: str, date: str) -> bool:
  """Reports whether `uv` was asked to resolve `version` against `date`."""
  fragment = f'--python-version {version} --exclude-newer {date} --index-url'
  return any(fragment in call for call in result.uv_calls)


def _run(tmp_path: pathlib.Path, *args: str, with_uv: bool = True) -> _Run:
  """Runs the script in an isolated CWD against a stub `uv`.

  Setting HOME is mandatory: the script prepends `$HOME/.local/bin` to PATH, so
  leaving the developer's real HOME in place would let a real `uv` shadow the
  stub and make these tests pass for the wrong reason.
  """
  (tmp_path / 'pyproject.toml').write_text(
      '[project]\nname = "x"\nversion = "0.1"\n'
  )
  stub_dir = tmp_path / 'bin'
  stub_dir.mkdir(exist_ok=True)
  call_log = tmp_path / 'uv-calls.log'
  if with_uv:
    stub = stub_dir / 'uv'
    stub.write_text(_UV_STUB.format(call_log=call_log, pin=_PIN))
    stub.chmod(0o755)
  process = subprocess.run(
      ['bash', str(_SCRIPT), *args],
      cwd=tmp_path,
      env={'PATH': f'{stub_dir}:/usr/bin:/bin', 'HOME': str(tmp_path)},
      capture_output=True,
      text=True,
      check=False,
  )
  return _Run(process, call_log)


def test_check_passes_when_every_file_matches(tmp_path: pathlib.Path) -> None:
  _write_all(tmp_path, _OLD_DATE)
  before = {v: _constraints(tmp_path, v).read_text() for v in _PYTHON_VERSIONS}

  result = _run(tmp_path, '--check')

  assert result.returncode == 0
  assert {
      v: _constraints(tmp_path, v).read_text() for v in _PYTHON_VERSIONS
  } == before


def test_check_reports_the_drifted_file_and_writes_nothing(
    tmp_path: pathlib.Path,
) -> None:
  _write_all(tmp_path, _OLD_DATE)
  drifted = _constraints(tmp_path, '3.12')
  drifted.write_text(_generated('3.12', _OLD_DATE, pin='stale-pin==0.0.1'))
  before = {v: _constraints(tmp_path, v).read_text() for v in _PYTHON_VERSIONS}

  result = _run(tmp_path, '--check')

  assert result.returncode == 1
  assert 'constraints-3.12.txt is OUT OF DATE!' in result.stdout
  assert {
      v: _constraints(tmp_path, v).read_text() for v in _PYTHON_VERSIONS
  } == before


def test_check_fails_when_a_file_is_missing(tmp_path: pathlib.Path) -> None:
  _write_all(tmp_path, _OLD_DATE)
  _constraints(tmp_path, '3.13').unlink()

  result = _run(tmp_path, '--check')

  assert result.returncode == 1
  assert 'constraints-3.13.txt is missing!' in result.stdout
  assert not _constraints(tmp_path, '3.13').exists()


def test_check_fails_when_the_header_records_no_snapshot_date(
    tmp_path: pathlib.Path,
) -> None:
  _write_all(tmp_path, _OLD_DATE)
  undated = _constraints(tmp_path, '3.12')
  undated.write_text(
      '# This file was autogenerated by uv via the following command:\n'
      '#    uv pip compile pyproject.toml --all-extras --python-version 3.12'
      ' --index-url https://pypi.org/simple -o constraints-3.12.txt\n'
      f'{_PIN}\n'
  )
  before = undated.read_text()

  result = _run(tmp_path, '--check')

  assert result.returncode == 1
  assert 'constraints-3.12.txt records no snapshot date!' in result.stdout
  assert undated.read_text() == before
  # Resolving an undated file would silently verify the pins against the live
  # index, so the script must not invoke uv for that version at all.
  assert not [c for c in result.uv_calls if '--python-version 3.12 ' in c]


def test_update_creates_every_file_and_exits_zero(
    tmp_path: pathlib.Path,
) -> None:
  result = _run(tmp_path)

  assert result.returncode == 0
  for version in _PYTHON_VERSIONS:
    assert _constraints(tmp_path, version).read_text() == _generated(
        version, _four_days_ago()
    )


def test_update_rewrites_a_drifted_file_and_exits_zero(
    tmp_path: pathlib.Path,
) -> None:
  _write_all(tmp_path, _OLD_DATE)
  drifted = _constraints(tmp_path, '3.11')
  drifted.write_text(_generated('3.11', _OLD_DATE, pin='stale-pin==0.0.1'))

  result = _run(tmp_path)

  assert result.returncode == 0
  assert 'constraints-3.11.txt has been updated locally.' in result.stdout
  assert drifted.read_text() == _generated('3.11', _OLD_DATE)


def test_update_reuses_the_recorded_snapshot_date(
    tmp_path: pathlib.Path,
) -> None:
  """Update mode must not advance the snapshot date of an existing file."""
  _write_all(tmp_path, _OLD_DATE)

  result = _run(tmp_path)

  assert result.returncode == 0
  assert _four_days_ago() != _OLD_DATE
  for version in _PYTHON_VERSIONS:
    assert _resolved_with(result, version, _OLD_DATE)
    assert _constraints(tmp_path, version).read_text() == _generated(
        version, _OLD_DATE
    )


def test_refresh_advances_the_snapshot_date(tmp_path: pathlib.Path) -> None:
  _write_all(tmp_path, _OLD_DATE)
  expected_date = _four_days_ago()

  result = _run(tmp_path, '--refresh')

  assert result.returncode == 0
  assert _OLD_DATE not in ' '.join(result.uv_calls)
  for version in _PYTHON_VERSIONS:
    assert _resolved_with(result, version, expected_date)
    assert _constraints(tmp_path, version).read_text() == _generated(
        version, expected_date
    )


def test_unknown_flag_is_a_usage_error(tmp_path: pathlib.Path) -> None:
  result = _run(tmp_path, '--nope')

  assert result.returncode == 2
  assert '--nope' in result.stderr
  assert 'Usage: ./scripts/update_constraints.sh' in result.stderr
  assert not list(tmp_path.glob('constraints-*'))


def test_check_and_refresh_together_are_a_usage_error(
    tmp_path: pathlib.Path,
) -> None:
  result = _run(tmp_path, '--check', '--refresh')

  assert result.returncode == 2
  assert '--check and --refresh cannot be combined' in result.stderr
  assert not list(tmp_path.glob('constraints-*'))


def test_missing_uv_fails_without_leaving_a_partial_artifact(
    tmp_path: pathlib.Path,
) -> None:
  result = _run(tmp_path, with_uv=False)

  assert result.returncode == 1
  assert not list(tmp_path.glob('constraints-*'))
