# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Runs `update_constraints.sh` against a stub `uv` that needs no network."""

from __future__ import annotations

import os
import pathlib
import shutil
import subprocess

from scripts import strip_constraint_provenance

_REPO_ROOT = (
    pathlib.Path(strip_constraint_provenance.__file__).resolve().parents[1]
)
_SCRIPT = _REPO_ROOT / 'scripts' / 'update_constraints.sh'
_HELPER = _REPO_ROOT / 'scripts' / 'strip_constraint_provenance.py'
_VERSIONS = ('3.10', '3.11', '3.12', '3.13', '3.14')
_DATE = '2026-07-26'

# What the stub `uv` writes: the shape uv emits when the script stabilizes the
# resolution with `--constraint`, so every block names the scratch file first.
_STUB_UV = """#!/bin/bash
set -e
out=""
prev=""
for arg in "$@"; do
  if [ "$prev" = "-o" ]; then out="$arg"; fi
  prev="$arg"
done
stable="${out%.new.tmp}.stable.tmp"
cat > "$out" <<EOF
# This file was autogenerated by uv via the following command:
#    uv pip compile <the stub rewrites this header>
a2a-sdk==1.1.1
    # via
    #   -c $stable
    #   google-adk (pyproject.toml)
defusedxml==0.7.1
    # via
    #   -c $stable
    #   llama-index-readers-file
    #   nltk
EOF
"""

# A `uv` that reports success without writing its output file. `tail` then
# fails while the filter still exits 0, which is the case `set -o pipefail`
# has to catch.
_STUB_UV_NO_OUTPUT = '#!/bin/bash\nexit 0\n'

_FILTERED_BODY = """a2a-sdk==1.1.1
    # via google-adk (pyproject.toml)
defusedxml==0.7.1
    # via
    #   llama-index-readers-file
    #   nltk
"""

_UNFILTERED_BODY = """a2a-sdk==1.1.1
    # via
    #   -c constraints-{ver}.txt.stable.tmp
    #   google-adk (pyproject.toml)
defusedxml==0.7.1
    # via
    #   -c constraints-{ver}.txt.stable.tmp
    #   llama-index-readers-file
    #   nltk
"""


def _header(ver: str) -> str:
  """Builds the header `update_constraints.sh` reconstructs for a version."""
  return (
      '# This file was autogenerated by uv via the following command:\n'
      f'#    uv pip compile pyproject.toml --all-extras --python-version {ver}'
      f' --exclude-newer {_DATE} --index-url https://pypi.org/simple'
      f' -o constraints-{ver}.txt\n'
  )


def _make_workspace(
    tmp_path: pathlib.Path, body: str, stub_uv: str = _STUB_UV
) -> pathlib.Path:
  """Lays out a throwaway checkout with a stub `uv` and the real script."""
  workspace = tmp_path / 'workspace'
  (workspace / 'scripts').mkdir(parents=True)
  (workspace / 'bin').mkdir()
  (workspace / 'home').mkdir()
  (workspace / 'pyproject.toml').write_text('[project]\n', encoding='utf-8')

  shutil.copy(_SCRIPT, workspace / 'scripts' / _SCRIPT.name)
  stub = workspace / 'bin' / 'uv'
  stub.write_text(stub_uv, encoding='utf-8')
  stub.chmod(0o755)

  for ver in _VERSIONS:
    (workspace / f'constraints-{ver}.txt').write_text(
        _header(ver) + body.format(ver=ver), encoding='utf-8'
    )
  return workspace


def _run(
    workspace: pathlib.Path, *args: str
) -> subprocess.CompletedProcess[str]:
  env = dict(os.environ)
  env['PATH'] = f'{workspace / "bin"}{os.pathsep}{env["PATH"]}'
  # The script prepends $HOME/.local/bin, so point HOME at an empty directory
  # to keep a real uv installation out of the way.
  env['HOME'] = str(workspace / 'home')
  return subprocess.run(
      ['bash', str(workspace / 'scripts' / _SCRIPT.name), *args],
      cwd=workspace,
      env=env,
      capture_output=True,
      text=True,
      check=False,
  )


def test_check_accepts_files_without_the_scratch_constraint(
    tmp_path: pathlib.Path,
) -> None:
  workspace = _make_workspace(tmp_path, _FILTERED_BODY)
  shutil.copy(_HELPER, workspace / 'scripts' / _HELPER.name)

  result = _run(workspace, '--check')

  assert result.returncode == 0, result.stdout + result.stderr


def test_check_rejects_files_that_still_name_the_scratch_constraint(
    tmp_path: pathlib.Path,
) -> None:
  workspace = _make_workspace(tmp_path, _UNFILTERED_BODY)
  shutil.copy(_HELPER, workspace / 'scripts' / _HELPER.name)

  result = _run(workspace, '--check')

  assert result.returncode == 1
  assert 'OUT OF DATE' in result.stdout


def test_a_missing_filter_does_not_truncate_the_committed_file(
    tmp_path: pathlib.Path,
) -> None:
  """A filter that cannot run must not overwrite the target with a stub."""
  workspace = _make_workspace(tmp_path, _FILTERED_BODY)
  # The helper is deliberately absent, so the last pipeline stage fails.
  target = workspace / 'constraints-3.10.txt'
  before = target.read_text(encoding='utf-8')

  result = _run(workspace)

  assert result.returncode != 0
  assert target.read_text(encoding='utf-8') == before


def test_a_failing_earlier_pipeline_stage_does_not_truncate_the_file(
    tmp_path: pathlib.Path,
) -> None:
  """Pins `set -o pipefail`.

  The filter is the last stage of the pipeline, so `set -e` alone already
  catches a failure there. It does not catch a failure in `tail`, whose
  status the pipeline discards. The stub `uv` reproduces that by exiting 0
  without writing the file `tail` then reads.
  """
  workspace = _make_workspace(
      tmp_path, _FILTERED_BODY, stub_uv=_STUB_UV_NO_OUTPUT
  )
  shutil.copy(_HELPER, workspace / 'scripts' / _HELPER.name)
  target = workspace / 'constraints-3.10.txt'
  before = target.read_text(encoding='utf-8')

  result = _run(workspace)

  assert result.returncode != 0
  assert target.read_text(encoding='utf-8') == before
