# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from __future__ import annotations

import pathlib
import re
import subprocess

import pytest

_REPO_ROOT = pathlib.Path(__file__).resolve().parents[3]
_SCRIPT = _REPO_ROOT / 'scripts' / 'update_constraints.sh'
# Discovered by glob rather than derived from _PYTHON_VERSIONS, so a sixth
# published file is guarded the moment it is committed.
_COMMITTED_CONSTRAINTS = sorted(_REPO_ROOT.glob('constraints-*.txt'))
_PYTHON_VERSIONS = ('3.10', '3.11', '3.12', '3.13', '3.14')
# The version whose header the malformed-header cases corrupt. The other four
# stay well-formed, so the same tests also pin per-file failure isolation.
_BROKEN_VERSION = '3.12'
_SNAPSHOT_DATE = '2026-01-02'
_PINNED_PACKAGE = 'typing-extensions==4.12.2'
_NO_SNAPSHOT_DATE_MESSAGE = (
    "has no single '--exclude-newer YYYY-MM-DD' snapshot date in its header,"
)
_RESOLUTION_FAILED_MESSAGE = '❌ Resolution failed for {target}.'
_SEED_LOG_NAME = 'uv-seed-sizes.log'
# A stub `uv` that records its argv and the size of the file named by `-o` as
# it found it, then writes that file instead of resolving against PyPI, so
# every path runs without network access. The recorded size is how the tests
# see the seeding: the script copies the committed pins into that file before
# it runs uv. The script keeps only `tail -n +3` of this output and rewrites
# the first two lines itself, hence the two throwaway header lines.
_UV_STUB = """#!/bin/bash
printf '%s\\n' "$*" >> "{call_log}"
while [ "$#" -gt 0 ]; do
  if [ "$1" = "-o" ]; then
    seed_size=0
    if [ -f "$2" ]; then seed_size=$(wc -c < "$2"); fi
    printf '%s\\n' "$seed_size" >> "{seed_log}"
    {outcome}
  fi
  shift
done
exit 1
"""
_RESOLVES = f"""printf '# header\\n# command\\n{_PINNED_PACKAGE}\\n' > "$2"
    exit 0"""
_FAILS_TO_RESOLVE = 'exit 1'


def _install_uv_stub(
    tmp_path: pathlib.Path, *, resolves: bool = True
) -> tuple[str, pathlib.Path]:
  """Installs the stub `uv`, returning the PATH to run with and its call log."""
  stub_dir = tmp_path / 'bin'
  stub_dir.mkdir()
  call_log = tmp_path / 'uv-calls.log'
  stub = stub_dir / 'uv'
  stub.write_text(
      _UV_STUB.format(
          call_log=call_log,
          seed_log=tmp_path / _SEED_LOG_NAME,
          outcome=_RESOLVES if resolves else _FAILS_TO_RESOLVE,
      )
  )
  stub.chmod(0o755)
  return f'{stub_dir}:/usr/bin:/bin', call_log


def _uv_calls(call_log: pathlib.Path) -> list[str]:
  """Returns the argv of each `uv` invocation the script made, in order."""
  return call_log.read_text().splitlines() if call_log.exists() else []


def _seed_sizes(tmp_path: pathlib.Path) -> list[int]:
  """Returns the byte size of the `-o` file at each `uv` call, in order."""
  seed_log = tmp_path / _SEED_LOG_NAME
  if not seed_log.exists():
    return []
  return [int(size) for size in seed_log.read_text().split()]


def _calls_for(call_log: pathlib.Path, version: str) -> list[str]:
  """Returns the `uv` invocations that resolved for `version`."""
  return [
      call
      for call in _uv_calls(call_log)
      if f'--python-version {version} ' in f'{call} '
  ]


def _constraints_file(version: str, snapshot_flags: str) -> str:
  """Returns a constraints file whose header carries `snapshot_flags` verbatim.

  The body matches what the script rebuilds from the stub `uv` output, so a
  file recording the snapshot date the script resolves against compares equal.
  """
  return (
      '# This file was autogenerated by uv via the following command:\n'
      '#    uv pip compile pyproject.toml --all-extras --no-emit-package'
      f' google-adk --python-version {version}{snapshot_flags} --index-url'
      f' https://pypi.org/simple -o constraints-{version}.txt\n'
      f'{_PINNED_PACKAGE}\n'
  )


def _generated_file(version: str, date: str = _SNAPSHOT_DATE) -> str:
  """Returns content byte-identical to what the script rebuilds for `version`."""
  return _constraints_file(version, f' --exclude-newer {date}')


def _write_constraints(tmp_path: pathlib.Path) -> None:
  """Writes a well-formed, up-to-date constraints file for every version."""
  for version in _PYTHON_VERSIONS:
    (tmp_path / f'constraints-{version}.txt').write_text(
        _generated_file(version)
    )


def _run(
    tmp_path: pathlib.Path, path: str, *args: str
) -> subprocess.CompletedProcess[str]:
  """Runs the real script in `tmp_path` with only the stub `uv` reachable.

  `HOME` must point at `tmp_path`: the script prepends `$HOME/.local/bin` to
  `PATH`, so a developer's real `uv` would otherwise shadow the stub and the
  tests would resolve against PyPI.
  """
  return subprocess.run(
      ['bash', str(_SCRIPT), *args],
      cwd=tmp_path,
      env={'PATH': path, 'HOME': str(tmp_path)},
      capture_output=True,
      text=True,
      check=False,
  )


@pytest.mark.parametrize(
    'content',
    [
        pytest.param(_constraints_file(_BROKEN_VERSION, ''), id='flag-absent'),
        pytest.param('', id='file-empty'),
        pytest.param(
            _constraints_file(_BROKEN_VERSION, ' --exclude-newer 2026-7-1'),
            id='date-not-zero-padded',
        ),
        pytest.param(
            _constraints_file(
                _BROKEN_VERSION,
                ' --exclude-newer 2026-01-02 --exclude-newer 2026-03-04',
            ),
            id='two-recorded-dates',
        ),
    ],
)
def test_check_mode_rejects_a_header_without_a_readable_snapshot_date(
    tmp_path: pathlib.Path, content: str
) -> None:
  path, call_log = _install_uv_stub(tmp_path)
  _write_constraints(tmp_path)
  broken = tmp_path / f'constraints-{_BROKEN_VERSION}.txt'
  broken.write_text(content)

  result = _run(tmp_path, path, '--check')

  assert result.returncode == 1, result.stdout
  assert (
      f'constraints-{_BROKEN_VERSION}.txt {_NO_SNAPSHOT_DATE_MESSAGE}'
      in result.stdout
  )
  # A corrupt header is not staleness. Reporting it as OUT OF DATE would send
  # the contributor to the updater, which overwrites the header and launders
  # the corruption into the published pins.
  assert (
      f'constraints-{_BROKEN_VERSION}.txt is OUT OF DATE' not in result.stdout
  )
  assert broken.read_text() == content
  # The fix itself: no resolution runs for the rejected file, so check mode
  # cannot fall back to the live index.
  assert _calls_for(call_log, _BROKEN_VERSION) == []
  for version in _PYTHON_VERSIONS:
    if version == _BROKEN_VERSION:
      continue
    assert f'✅ constraints-{version}.txt is up-to-date.' in result.stdout


def test_check_mode_resolves_against_the_recorded_snapshot_date(
    tmp_path: pathlib.Path,
) -> None:
  path, call_log = _install_uv_stub(tmp_path)
  _write_constraints(tmp_path)

  result = _run(tmp_path, path, '--check')

  assert result.returncode == 0, result.stdout
  calls = _uv_calls(call_log)
  assert len(calls) == len(_PYTHON_VERSIONS)
  for call in calls:
    assert f'--exclude-newer {_SNAPSHOT_DATE}' in call


def test_check_mode_reports_missing_files_without_resolving(
    tmp_path: pathlib.Path,
) -> None:
  path, call_log = _install_uv_stub(tmp_path)

  result = _run(tmp_path, path, '--check')

  assert result.returncode == 1, result.stdout
  for version in _PYTHON_VERSIONS:
    assert f'❌ constraints-{version}.txt is missing!' in result.stdout
  # The missing-file branch continues before the header is read, so the two
  # error paths must never fire for the same file.
  assert _NO_SNAPSHOT_DATE_MESSAGE not in result.stdout
  assert _uv_calls(call_log) == []


def test_update_mode_regenerates_a_file_with_a_malformed_header(
    tmp_path: pathlib.Path,
) -> None:
  path, call_log = _install_uv_stub(tmp_path)
  _write_constraints(tmp_path)
  broken = tmp_path / f'constraints-{_BROKEN_VERSION}.txt'
  broken.write_text(_constraints_file(_BROKEN_VERSION, ''))

  result = _run(tmp_path, path)

  assert result.returncode == 1, result.stdout
  assert _NO_SNAPSHOT_DATE_MESSAGE not in result.stdout
  assert (
      f'🔄 constraints-{_BROKEN_VERSION}.txt was OUT OF DATE. Updating it'
      ' automatically...'
      in result.stdout
  )
  calls = _calls_for(call_log, _BROKEN_VERSION)
  assert len(calls) == 1
  # Read the date back out of the recorded argv rather than recomputing
  # `today - 4d` here, which would race a midnight rollover.
  match = re.search(r'--exclude-newer (\d{4}-\d{2}-\d{2})', calls[0])
  assert match is not None, calls[0]
  assert broken.read_text() == _generated_file(_BROKEN_VERSION, match.group(1))


def test_uv_excludes_the_self_pin_and_starts_from_the_committed_pins(
    tmp_path: pathlib.Path,
) -> None:
  path, call_log = _install_uv_stub(tmp_path)
  _write_constraints(tmp_path)

  result = _run(tmp_path, path, '--check')

  assert result.returncode == 0, result.stdout
  calls = _uv_calls(call_log)
  assert len(calls) == len(_PYTHON_VERSIONS)
  for call in calls:
    # The community and toolbox extras depend back on google-adk, so uv
    # resolves the published release and pins it into the file that is applied
    # to the very install it constrains.
    assert '--no-emit-package google-adk' in call
    # A --constraint file is recorded as a resolution source, which stamps its
    # path into every published annotation block.
    assert '--constraint' not in call
  # The committed pins reach uv as its seeded output file instead.
  assert _seed_sizes(tmp_path) == [
      len(_generated_file(version).encode()) for version in _PYTHON_VERSIONS
  ]
  assert list(tmp_path.glob('constraints-*.tmp')) == []


@pytest.mark.parametrize(
    'args',
    [pytest.param(('--check',), id='check'), pytest.param((), id='update')],
)
def test_a_failed_resolution_is_reported_without_a_retry(
    tmp_path: pathlib.Path, args: tuple[str, ...]
) -> None:
  path, call_log = _install_uv_stub(tmp_path, resolves=False)
  _write_constraints(tmp_path)

  result = _run(tmp_path, path, *args)

  assert result.returncode == 1, result.stdout
  for version in _PYTHON_VERSIONS:
    target = f'constraints-{version}.txt'
    assert _RESOLUTION_FAILED_MESSAGE.format(target=target) in result.stdout
    assert (tmp_path / target).read_text() == _generated_file(version)
    # Seeded pins are preferences, so a stale pin cannot abort the resolution
    # and there is no unconstrained second attempt to fall back to.
    assert len(_calls_for(call_log, version)) == 1
  assert list(tmp_path.glob('constraints-*.tmp')) == []


def test_every_published_constraints_file_is_discovered() -> None:
  # An empty glob would silently turn each guard below into zero tests.
  assert [path.name for path in _COMMITTED_CONSTRAINTS] == [
      f'constraints-{version}.txt' for version in _PYTHON_VERSIONS
  ]


@pytest.mark.parametrize(
    'constraints', _COMMITTED_CONSTRAINTS, ids=lambda path: path.name
)
def test_no_published_file_pins_the_package_being_installed(
    constraints: pathlib.Path,
) -> None:
  assert not re.search(
      r'^google-adk==', constraints.read_text(), flags=re.MULTILINE
  ), (
      f'{constraints.name} pins google-adk. README.md applies this file to the'
      ' install of google-adk itself, so the pin holds the user at whatever'
      ' release was current when the file was last regenerated.'
  )


@pytest.mark.parametrize(
    'constraints', _COMMITTED_CONSTRAINTS, ids=lambda path: path.name
)
def test_every_published_file_still_pins_the_community_package(
    constraints: pathlib.Path,
) -> None:
  # google-adk-community is a genuine transitive dependency, so it proves
  # --no-emit-package stayed scoped to the package under installation.
  assert re.search(
      r'^google-adk-community==', constraints.read_text(), flags=re.MULTILINE
  ), f'{constraints.name} no longer pins google-adk-community.'


@pytest.mark.parametrize(
    'constraints', _COMMITTED_CONSTRAINTS, ids=lambda path: path.name
)
def test_no_published_file_names_the_scratch_constraint(
    constraints: pathlib.Path,
) -> None:
  assert '.stable.tmp' not in constraints.read_text(), (
      f'{constraints.name} names a scratch file the reader never has, so the'
      ' command in its own header does not reproduce it.'
  )


@pytest.mark.parametrize(
    'constraints', _COMMITTED_CONSTRAINTS, ids=lambda path: path.name
)
def test_every_published_header_records_the_no_emit_flag(
    constraints: pathlib.Path,
) -> None:
  header = constraints.read_text().splitlines()[1]

  assert header.startswith('#    uv pip compile'), header
  assert '--no-emit-package google-adk' in header, header
