# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Guard tests for the weekly constraints refresh.

The ``Update Dependency Constraints`` workflow runs
``scripts/update_constraints.sh`` in update mode and opens a bot pull request
with the result. It must tolerate exit ``1``, which is the normal outcome of a
scheduled run because ``--exclude-newer`` moves every time, and it must stop on
exit ``2``, a failed resolution. A failed resolution leaves its own target file
untouched while the other versions are rewritten, so the exit code is the only
signal that the tree mixes fresh pins with a stale one.

Both halves are hermetic. The script runs against a stub ``uv``, and the
workflow step runs against a stub script, so neither reaches PyPI nor needs a
real ``uv`` on the machine.
"""

from __future__ import annotations

from collections.abc import Mapping
from collections.abc import Sequence
from pathlib import Path
import subprocess

import pytest
import yaml

_REPO_ROOT = Path(__file__).parents[2]
_SCRIPT = _REPO_ROOT / 'scripts' / 'update_constraints.sh'
_WORKFLOW = _REPO_ROOT / '.github' / 'workflows' / 'update-constraints.yml'

_PYTHON_VERSIONS = ('3.10', '3.11', '3.12', '3.13', '3.14')
_REGENERATE_STEP = 'Regenerate constraints files'

# A `uv pip compile` stand-in. It reads the output path from `-o` rather than
# from the last argument, because update_constraints.sh appends
# `--constraint <file>` after `-o <file>`; a stub that took the last argument
# would write the resolution over the stabilizer instead.
_STUB_UV = """#!/bin/bash
out=""
ver=""
prev=""
for arg in "$@"; do
  case "$prev" in
    -o|--output-file) out="$arg" ;;
    --python-version) ver="$arg" ;;
  esac
  prev="$arg"
done
for refused in ${STUB_UV_FAIL_VERSIONS:-}; do
  if [ "$refused" = "$ver" ]; then
    echo "stub uv: cannot resolve for Python $ver" >&2
    exit 1
  fi
done
{
  echo "# This file was autogenerated by uv via the following command:"
  echo "#    stub uv pip compile"
  echo "pinned-for-${ver}==1.0.0"
} > "$out"
"""


@pytest.fixture(name='checkout')
def checkout_fixture(tmp_path: Path) -> Path:
  """Builds a throwaway checkout that runs the real script against a stub uv.

  The checkout holds a minimal ``pyproject.toml``, a placeholder
  ``constraints-<ver>.txt`` for every supported interpreter, and an executable
  ``bin/uv`` stub.
  """
  bin_dir = tmp_path / 'bin'
  bin_dir.mkdir()
  stub = bin_dir / 'uv'
  stub.write_text(_STUB_UV, encoding='utf-8')
  stub.chmod(0o755)

  scripts_dir = tmp_path / 'scripts'
  scripts_dir.mkdir()
  target = scripts_dir / 'update_constraints.sh'
  target.write_bytes(_SCRIPT.read_bytes())
  target.chmod(0o755)

  (tmp_path / 'pyproject.toml').write_text(
      '[project]\nname = "stub"\nversion = "0"\n', encoding='utf-8'
  )
  for version in _PYTHON_VERSIONS:
    (tmp_path / f'constraints-{version}.txt').write_text(
        'placeholder\n', encoding='utf-8'
    )
  return tmp_path


def _run_script(
    checkout: Path,
    *,
    fail_versions: Sequence[str] = (),
    check: bool = False,
) -> int:
  """Runs the script in the checkout and returns its exit code.

  Args:
    checkout: The throwaway checkout to run in.
    fail_versions: Interpreter versions the stub ``uv`` refuses to resolve.
    check: Whether to pass ``--check``.
  """
  command = [str(checkout / 'scripts' / 'update_constraints.sh')]
  if check:
    command.append('--check')
  # HOME must not hold a real uv: the script prepends $HOME/.local/bin to PATH.
  env = {
      'PATH': f'{checkout / "bin"}:/usr/bin:/bin',
      'HOME': str(checkout / 'home'),
      'STUB_UV_FAIL_VERSIONS': ' '.join(fail_versions),
  }
  return subprocess.run(
      command,
      cwd=checkout,
      env=env,
      capture_output=True,
      text=True,
      check=False,
  ).returncode


def _read_constraints(checkout: Path) -> Mapping[str, str]:
  """Returns the constraints file contents keyed by interpreter version."""
  return {
      version: (
          (checkout / f'constraints-{version}.txt').read_text(encoding='utf-8')
      )
      for version in _PYTHON_VERSIONS
  }


@pytest.mark.parametrize(
    'fail_versions',
    [_PYTHON_VERSIONS, ('3.12',)],
    ids=['every_version_fails', 'one_version_fails'],
)
def test_script_exits_2_when_a_resolution_fails(
    checkout: Path, fail_versions: Sequence[str]
) -> None:
  """A failed resolution reports 2, and outranks the rewrites around it."""
  before = _read_constraints(checkout)

  assert _run_script(checkout, fail_versions=fail_versions) == 2

  after = _read_constraints(checkout)
  for version in _PYTHON_VERSIONS:
    if version in fail_versions:
      # The failure leaves the stale file in place, so only the exit code can
      # report it.
      assert after[version] == before[version]
    else:
      assert after[version] != before[version]


def test_script_exits_1_when_it_rewrites_the_files(checkout: Path) -> None:
  """Rewriting every file reports 1, the normal scheduled outcome."""
  before = _read_constraints(checkout)

  assert _run_script(checkout) == 1

  assert _read_constraints(checkout) != before


def test_script_exits_0_when_everything_is_current(checkout: Path) -> None:
  """A re-run over already current files reports 0 and rewrites nothing."""
  assert _run_script(checkout) == 1
  after_first_run = _read_constraints(checkout)

  assert _run_script(checkout) == 0

  assert _read_constraints(checkout) == after_first_run


def test_check_mode_exits_2_when_a_resolution_fails(checkout: Path) -> None:
  """--check reports a failed resolution as 2, not as ordinary drift."""
  before = _read_constraints(checkout)

  assert _run_script(checkout, fail_versions=('3.12',), check=True) == 2

  assert _read_constraints(checkout) == before


def test_check_mode_exits_1_on_drift(checkout: Path) -> None:
  """--check still reports drift as 1, so the pre-commit hook is unchanged."""
  before = _read_constraints(checkout)

  assert _run_script(checkout, check=True) == 1

  assert _read_constraints(checkout) == before


def _regenerate_step_body() -> str:
  """Returns the ``run:`` body of the workflow's regeneration step."""
  workflow = yaml.safe_load(_WORKFLOW.read_text(encoding='utf-8'))
  (job,) = workflow['jobs'].values()
  bodies = [
      step['run']
      for step in job['steps']
      if step.get('name') == _REGENERATE_STEP
  ]
  assert (
      len(bodies) == 1
  ), f'{_WORKFLOW} must have exactly one {_REGENERATE_STEP!r} step'
  return bodies[0]


def _run_regenerate_step(tmp_path: Path, script_exit: int) -> int:
  """Runs the shipped step body over a script stubbed to a given exit code."""
  scripts_dir = tmp_path / 'scripts'
  scripts_dir.mkdir()
  script = scripts_dir / 'update_constraints.sh'
  script.write_text(f'#!/bin/bash\nexit {script_exit}\n', encoding='utf-8')
  script.chmod(0o755)

  step = tmp_path / 'step.sh'
  step.write_text(_regenerate_step_body(), encoding='utf-8')
  # GitHub Actions runs a `run:` block as `bash -e {0}`.
  return subprocess.run(
      ['bash', '-e', 'step.sh'],
      cwd=tmp_path,
      capture_output=True,
      text=True,
      check=False,
  ).returncode


@pytest.mark.parametrize('script_exit', [0, 1])
def test_workflow_step_accepts_nothing_to_do_and_rewritten(
    tmp_path: Path, script_exit: int
) -> None:
  """The step tolerates 0 and 1, so a scheduled rewrite still opens a PR."""
  assert _run_regenerate_step(tmp_path, script_exit) == 0


def test_workflow_step_rejects_a_failed_resolution(tmp_path: Path) -> None:
  """The step fails on 2, so no PR mixes fresh pins with a stale one."""
  assert _run_regenerate_step(tmp_path, 2) != 0


def test_workflow_runs_weekly_and_only_upstream() -> None:
  """The workflow is weekly, manual, and inert on forks."""
  workflow = yaml.safe_load(_WORKFLOW.read_text(encoding='utf-8'))
  # `on` is the YAML 1.1 boolean True, which safe_load produces as a key.
  triggers = workflow[True]
  (job,) = workflow['jobs'].values()

  assert triggers['schedule'] == [{'cron': '0 7 * * 1'}]
  assert 'workflow_dispatch' in triggers
  assert job['if'] == "github.repository == 'google/adk-python'"
