# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Guard tests for the repository paths ``README.md`` tells users to download.

``README.md`` publishes URLs that resolve back into this repository: the logo,
the ``docs/guides`` and ``contributing/samples`` directories, and the
``constraints-<ver>.txt`` file its install recipe tells users to ``curl``.
Nothing asserted that those paths exist. For the whole window in which no
constraints file was committed, every step of the documented install -- the
``curl``, the ``pip install -c``, the ``rm`` -- produced a wrong result and the
test suite stayed green.

These tests read the real ``README.md``, the real
``scripts/update_constraints.sh`` and the real committed constraints files:

* Every repository path the README names exists in the checkout.
* Every interpreter in the script's ``PYTHON_VERSIONS`` array has a non-empty
  constraints file, and that list agrees with the ``pyproject.toml``
  classifiers.
* Each constraints file keeps the two-line header that
  ``scripts/update_constraints.sh --check`` parses its snapshot date out of,
  and pins every requirement exactly.
* The README still documents the install recipe, so the guard cannot be
  defused by deleting its subject.

Nothing here starts a subprocess or touches the network. Running
``scripts/update_constraints.sh`` would cost five resolutions against PyPI and
rewrite tracked files.
"""

from __future__ import annotations

import re

try:
  import tomllib
except ImportError:
  import tomli as tomllib

import pytest

from .isolated_import_utils import REPO_ROOT as _REPO_ROOT

# The single source of truth for which interpreters get a constraints file.
_GENERATOR_SCRIPT = 'scripts/update_constraints.sh'

_UV_BANNER = '# This file was autogenerated by uv via the following command:'

# ``update_constraints.sh --check`` locates this line with
# ``grep -h "#    uv pip compile"``, so the four spaces are load-bearing.
_UV_COMMAND_PREFIX = '#    uv pip compile '

_EXCLUDE_NEWER_RE = re.compile(r'--exclude-newer \d{4}-\d{2}-\d{2}')

_CONSTRAINTS_NAME_RE = re.compile(r'constraints-\d+\.\d+\.txt')

# A README URL that resolves into this repository, capturing the
# repository-relative path. Anchoring on the raw host or on ``/blob/`` and
# ``/tree/`` is what keeps the CI badge out: ``github.com/google/adk-python/
# actions/workflows/...`` is not repository content, and the workflow it
# renders actually lives under ``.github/workflows/``.
_REPO_URL_RE = re.compile(
    r'https://(?:raw\.githubusercontent\.com/google/adk-python'
    r'|github\.com/google/adk-python/(?:blob|tree))'
    r'/[^/\s]+/([^\s"\'`)>]+)'
)

# A relative markdown link, which names a path in the checkout. Absolute URLs,
# in-page anchors and site-absolute paths are not repository content.
_RELATIVE_LINK_RE = re.compile(r'\]\((?![\w.+-]+:|[#/])([^)\s]+)\)')

_PYTHON_VERSIONS_RE = re.compile(
    r'^PYTHON_VERSIONS=\((?P<versions>[^)]*)\)', re.MULTILINE
)

_CLASSIFIER_RE = re.compile(r'^Programming Language :: Python :: (\d+\.\d+)$')

if not (_REPO_ROOT / _GENERATOR_SCRIPT).is_file():
  pytest.skip(
      'Constraints checks need the source checkout layout.',
      allow_module_level=True,
  )


def _repo_paths_in(markdown: str) -> tuple[str, ...]:
  """Returns the sorted repository-relative paths ``markdown`` points at."""
  paths = _REPO_URL_RE.findall(markdown) + _RELATIVE_LINK_RE.findall(markdown)
  return tuple(sorted({path.rstrip('.,') for path in paths}))


def _parse_python_versions(script: str) -> tuple[str, ...]:
  """Returns the interpreters in the script's ``PYTHON_VERSIONS`` array."""
  match = _PYTHON_VERSIONS_RE.search(script)
  if match is None:
    return ()
  return tuple(re.findall(r'\d+\.\d+', match['versions']))


_README_PATH = _REPO_ROOT / 'README.md'
_README = _README_PATH.read_text(encoding='utf-8')
_README_REPO_PATHS = _repo_paths_in(_README)
_PYTHON_VERSIONS = _parse_python_versions(
    (_REPO_ROOT / _GENERATOR_SCRIPT).read_text(encoding='utf-8')
)


def _classified_python_versions() -> set[str]:
  """Returns the Python versions pyproject.toml advertises support for."""
  with (_REPO_ROOT / 'pyproject.toml').open('rb') as fh:
    classifiers = tomllib.load(fh)['project']['classifiers']
  return {
      match[1]
      for classifier in classifiers
      if (match := _CLASSIFIER_RE.match(classifier))
  }


def _constraints_lines(version: str) -> list[str]:
  """Returns the lines of the committed constraints file for ``version``."""
  path = _REPO_ROOT / f'constraints-{version}.txt'
  return path.read_text(encoding='utf-8').splitlines()


def test_repo_paths_in_captures_only_paths_into_this_repository() -> None:
  markdown = '\n'.join([
      (
          '<img src="https://raw.githubusercontent.com/google/adk-python/main/'
          'assets/logo.png"/>'
      ),
      (
          'curl -o c.txt'
          ' https://raw.githubusercontent.com/google/adk-python/main/c.txt'
      ),
      '[docs](https://github.com/google/adk-python/tree/main/docs/guides)',
      'See https://github.com/google/adk-python/blob/v1/NOTICE.',
      '[contributing](CONTRIBUTING.md) and [license](LICENSE)',
      # The CI badge names a github.com page, not a file in the tree.
      (
          '[![CI](https://github.com/google/adk-python/actions/workflows/'
          'ci.yml/badge.svg)](https://github.com/google/adk-python/actions/'
          'workflows/ci.yml)'
      ),
      # Another repository's files are not ours to verify.
      'https://raw.githubusercontent.com/other/repo/main/elsewhere.txt',
      # Neither an in-page anchor nor an absolute URL names a checkout path.
      '[section](#installation) and [docs](https://google.github.io/adk-docs/)',
  ])

  assert _repo_paths_in(markdown) == (
      'CONTRIBUTING.md',
      'LICENSE',
      'NOTICE',
      'assets/logo.png',
      'c.txt',
      'docs/guides',
  )


def test_parse_python_versions_reads_the_bash_array() -> None:
  assert _parse_python_versions(
      'EXIT_CODE=0\nPYTHON_VERSIONS=("3.10" "3.14")\n'
  ) == ('3.10', '3.14')


def test_parse_python_versions_finds_nothing_without_the_array() -> None:
  assert _parse_python_versions('EXIT_CODE=0\n') == ()


def test_readme_reference_extraction_is_not_empty() -> None:
  """Proves the extraction still matches, so the guard cannot pass vacuously."""
  downloads = [
      path
      for path in _README_REPO_PATHS
      if _CONSTRAINTS_NAME_RE.fullmatch(path)
  ]

  assert _README_REPO_PATHS, (
      f'No repository path was extracted from {_README_PATH}. Either the '
      'README stopped linking to this repository or the extraction in this '
      'module no longer matches its links, which would leave every link '
      'unguarded.'
  )
  assert downloads, (
      f'{_README_PATH} no longer names a constraints-<ver>.txt path this '
      'extraction recognises, so the install recipe that this module exists '
      'to protect is no longer covered.'
  )


@pytest.mark.parametrize('repo_path', _README_REPO_PATHS)
def test_readme_repo_references_resolve(repo_path: str) -> None:
  assert (_REPO_ROOT / repo_path).exists(), (
      f'{_README_PATH} points users at {repo_path!r}, which this repository '
      'does not contain. A reader who follows the README downloads a 404 '
      'page, or clicks a dead link. Commit the path or drop the reference.'
  )


def test_readme_documents_the_constraints_install_recipe() -> None:
  """The install recipe the other tests protect must stay documented."""
  assert re.search(r'curl\b[^\n]*constraints-\d+\.\d+\.txt', _README), (
      f'{_README_PATH} no longer tells users to download a constraints file. '
      'If that is intended, delete this module too, because the rest of it '
      'guards a contract nobody publishes any more.'
  )
  assert re.search(
      r'pip install google-adk -c constraints-\d+\.\d+\.txt', _README
  ), (
      f'{_README_PATH} no longer shows the -c constraints-<ver>.txt install. '
      'Downloading the file is pointless unless the README also says to pass '
      'it to pip.'
  )


def test_supported_versions_match_pyproject_classifiers() -> None:
  """The script and the package must agree on the supported interpreters."""
  classified = _classified_python_versions()

  assert _PYTHON_VERSIONS, (
      f'No PYTHON_VERSIONS array was parsed out of {_GENERATOR_SCRIPT}, so '
      'the per-version tests in this module would collect no cases at all.'
  )
  assert classified, (
      'pyproject.toml declares no "Programming Language :: Python :: 3.x" '
      'classifier, so there is nothing to check the generator script against.'
  )
  assert set(_PYTHON_VERSIONS) == classified, (
      f'{_GENERATOR_SCRIPT} generates constraints for '
      f'{sorted(_PYTHON_VERSIONS)} but pyproject.toml advertises support for '
      f'{sorted(classified)}. An interpreter in only one of the two lists is '
      'either supported with no published constraints file, or pinned for a '
      'version the package does not claim to support.'
  )


@pytest.mark.parametrize('version', _PYTHON_VERSIONS)
def test_constraints_file_exists_for_every_supported_version(
    version: str,
) -> None:
  path = _REPO_ROOT / f'constraints-{version}.txt'

  assert path.is_file(), (
      f'{_GENERATOR_SCRIPT} generates {path.name} and README.md documents '
      f'downloading it, but it is not committed. Users on Python {version} '
      'who follow the install instructions save a 404 page and then fail to '
      'install. Run the generator script and commit the result.'
  )
  assert path.stat().st_size > 0, (
      f'{path.name} is empty, so "pip install google-adk -c {path.name}" '
      'pins nothing at all while appearing to work.'
  )


@pytest.mark.parametrize('version', _PYTHON_VERSIONS)
def test_constraints_header_is_machine_readable(version: str) -> None:
  """The two-line header is what ``--check`` reads the snapshot date from."""
  name = f'constraints-{version}.txt'
  lines = _constraints_lines(version)

  assert len(lines) >= 2, f'{name} is too short to carry its two-line header.'
  assert lines[0] == _UV_BANNER, (
      f'Line 1 of {name} is {lines[0]!r}, not the uv banner. The generator '
      'script writes this header itself; a hand-edited file will be '
      'overwritten on the next run.'
  )
  command = lines[1]
  assert command.startswith(_UV_COMMAND_PREFIX), (
      f'Line 2 of {name} must start with the literal {_UV_COMMAND_PREFIX!r}. '
      f'{_GENERATOR_SCRIPT} --check finds this line by grepping for that '
      'exact prefix, four spaces included, so a reformatted header makes the '
      'drift check silently compare against nothing.'
  )
  assert f'--python-version {version}' in command, (
      f'{name} records a --python-version that disagrees with its name: '
      f'{command!r}. The file then pins the wrong interpreter.'
  )
  assert _EXCLUDE_NEWER_RE.search(command), (
      f'{name} records no --exclude-newer YYYY-MM-DD date. '
      f'{_GENERATOR_SCRIPT} --check re-runs the resolution with the date it '
      'reads back out of this line; without it, --check resolves against '
      'today and reports drift on every run.'
  )
  assert command.endswith(f'-o {name}'), (
      f'The command recorded in {name} writes to a different file: '
      f'{command!r}. Regenerate it with {_GENERATOR_SCRIPT}.'
  )


@pytest.mark.parametrize('version', _PYTHON_VERSIONS)
def test_constraints_files_pin_exact_versions(version: str) -> None:
  """A constraints file that does not pin exactly constrains nothing."""
  name = f'constraints-{version}.txt'
  unpinned = [
      (number, line)
      for number, line in enumerate(_constraints_lines(version), start=1)
      if line.strip() and not line.startswith(('#', ' ')) and '==' not in line
  ]

  assert not unpinned, (
      f'{len(unpinned)} requirement line(s) in {name} do not pin an exact '
      f'version. The first is line {unpinned[0][0]}: {unpinned[0][1]!r}. A '
      'range lets the resolver install a release that was never tested, '
      'which is the failure the file exists to prevent.'
  )
