# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Guard tests for the published ``constraints-*.txt`` contract.

``README.md`` tells users to install with ``pip install google-adk -c
constraints-<ver>.txt``, so those files must be committed and must stay
readable by ``scripts/update_constraints.sh --check``. These tests pin the
properties whose absence kept the lint gate permanently red:

* The files exist for every interpreter the script generates.
* Their two-line header is the one the script reconstructs. ``--check`` parses
  ``--exclude-newer`` back out of line 2, so a hand-typed ``uv`` invocation
  would silently make the check date-unstable.
* No ``-c`` constraint-source annotation leaked in. Passing the committed file
  to uv via ``--constraint`` used to record it as a resolution *source* in every
  ``# via`` block, which made the regenerated file permanently differ from the
  committed one.
* ``google-adk`` does not pin itself. ``--all-extras`` pulls in the
  ``community`` extra, whose ``google-adk-community`` depends back on
  ``google-adk``, so uv emits a ``google-adk==`` line unless told not to. The
  files are regenerated only when ``pyproject.toml`` dependencies change, so
  that pin goes stale on the next release and downgrades the very package the
  README tells users to install.

Plus the direct regression guard: ``pre-commit`` must not shell out to the
network-dependent update script, because the CI lint job runs
``pre-commit run --all-files`` on every pull request.
"""

from __future__ import annotations

from pathlib import Path
import re

import pytest
import yaml

try:
  import tomllib
except ImportError:
  import tomli as tomllib

# tests/unittests/<this file> -> the repo root. Kept lexical rather than
# resolved: the test tree may be symlinked.
_REPO_ROOT = Path(__file__).parents[2]
_SCRIPT_PATH = _REPO_ROOT / 'scripts' / 'update_constraints.sh'

if not _SCRIPT_PATH.is_file():
  pytest.skip(
      'Not a full source checkout: scripts/update_constraints.sh is absent.',
      allow_module_level=True,
  )


def _parse_python_versions(script: str) -> tuple[str, ...]:
  """Extracts the interpreters from the script's PYTHON_VERSIONS bash array.

  The script is the single source of truth for which constraints files must
  exist. An unparseable array yields an empty tuple, which
  ``test_script_versions_match_python_classifiers`` reports as a failure.
  """
  array = re.findall(r'^PYTHON_VERSIONS=\((.*)\)$', script, re.MULTILINE)
  return tuple(re.findall(r'\d+\.\d+', ' '.join(array)))


_PYTHON_VERSIONS = _parse_python_versions(_SCRIPT_PATH.read_text())

# The two-line header scripts/update_constraints.sh reconstructs verbatim.
_HEADER_LINE_1 = (
    '# This file was autogenerated by uv via the following command:'
)
_HEADER_LINE_2 = (
    r'^#\s+uv pip compile pyproject\.toml --all-extras'
    r' --no-emit-package google-adk --python-version {ver}'
    r' --exclude-newer \d{{4}}-\d{{2}}-\d{{2}}'
    r' --index-url https://pypi\.org/simple -o constraints-{ver}\.txt$'
)
# The corruption that --constraint injects into every "# via" block. uv writes
# the source *indented inside* that block ('    #   -c constraints-3.11.txt'),
# so '#' must not be anchored to column 0, and the path must not be assumed to
# end in .tmp -- passing the committed file to --constraint directly leaks its
# real name. Either anchor alone scores 0 against a genuinely corrupted file.
_LEAKED_ANNOTATION = re.compile(r'^\s*#\s+-c .*$', re.MULTILINE)
# A pin of the package the constraints file is meant to constrain the install
# of. Matches the emitted pin, not the "# via google-adk (pyproject.toml)"
# provenance comments or the google-adk-community dependency.
_SELF_PIN = re.compile(r'^google-adk==.*$', re.MULTILINE)


def _constraints_path(version: str) -> Path:
  return _REPO_ROOT / f'constraints-{version}.txt'


@pytest.mark.parametrize('version', _PYTHON_VERSIONS)
def test_constraints_file_exists_for_every_supported_version(
    version: str,
) -> None:
  path = _constraints_path(version)
  assert path.is_file(), (
      f'{path.name} is missing. README.md documents downloading it, and'
      ' ./scripts/update_constraints.sh --check fails without it.'
  )
  assert path.stat().st_size > 0, f'{path.name} is empty.'


@pytest.mark.parametrize('version', _PYTHON_VERSIONS)
def test_constraints_header_is_script_generated(version: str) -> None:
  path = _constraints_path(version)
  header = path.read_text().splitlines()[:2]

  assert (
      header[0] == _HEADER_LINE_1
  ), f'{path.name} line 1 is not the uv autogeneration banner.'
  assert re.match(_HEADER_LINE_2.format(ver=re.escape(version)), header[1]), (
      f'{path.name} line 2 is not the command'
      ' ./scripts/update_constraints.sh reconstructs, so --check cannot parse'
      f' its --exclude-newer date back out. Got: {header[1]!r}'
  )


@pytest.mark.parametrize('version', _PYTHON_VERSIONS)
def test_constraints_files_have_no_annotation_leakage(version: str) -> None:
  path = _constraints_path(version)
  leaks = _LEAKED_ANNOTATION.findall(path.read_text())
  assert not leaks, (
      f'{path.name} carries {len(leaks)} uv constraint-source annotations,'
      f' e.g. {leaks[0]!r}. The generator must seed uv with the committed'
      ' output file, never pass it via --constraint: uv records a --constraint'
      ' input as a resolution source in every "# via" block, so the'
      ' regenerated file can never match the committed one and --check reports'
      ' a permanent diff.'
  )


@pytest.mark.parametrize('version', _PYTHON_VERSIONS)
def test_constraints_files_do_not_pin_google_adk(version: str) -> None:
  path = _constraints_path(version)
  pins = _SELF_PIN.findall(path.read_text())
  assert not pins, (
      f'{path.name} pins google-adk itself: {pins}. README.md documents'
      ' `pip install google-adk -c constraints-<ver>.txt`, so this pin caps'
      ' the package being installed at whatever version was current when the'
      ' file was last regenerated, silently downgrading the user on the next'
      ' release. The generator must pass'
      ' `--no-emit-package google-adk` to uv.'
  )


@pytest.mark.parametrize('version', _PYTHON_VERSIONS)
def test_constraints_files_still_pin_google_adk_community(version: str) -> None:
  """``--no-emit-package`` must drop only the package under installation.

  ``google-adk-community`` is a genuine transitive dependency reached through
  the ``community`` extra, and is exactly the kind of package these files
  exist to pin. Dropping it too would be a silent loss of coverage that
  ``test_constraints_files_do_not_pin_google_adk`` alone would not notice.
  """
  path = _constraints_path(version)
  assert re.search(
      r'^google-adk-community==', path.read_text(), re.MULTILINE
  ), (
      f'{path.name} no longer pins google-adk-community.'
      ' --no-emit-package must exclude google-adk only.'
  )


def test_script_versions_match_python_classifiers() -> None:
  with (_REPO_ROOT / 'pyproject.toml').open('rb') as fh:
    classifiers = tomllib.load(fh)['project']['classifiers']

  classified = {
      c.rsplit('::', 1)[1].strip()
      for c in classifiers
      if c.startswith('Programming Language :: Python :: 3.')
  }
  assert set(_PYTHON_VERSIONS) == classified, (
      'scripts/update_constraints.sh and the pyproject.toml Python'
      ' classifiers disagree on the supported interpreters.'
  )


def test_precommit_does_not_run_constraints_script() -> None:
  config = yaml.safe_load((_REPO_ROOT / '.pre-commit-config.yaml').read_text())

  entries = [
      hook.get('entry', '')
      for repo in config['repos']
      for hook in repo.get('hooks', [])
  ]
  assert not [e for e in entries if 'update_constraints.sh' in e], (
      'The constraints updater is back in .pre-commit-config.yaml. The CI'
      ' lint job runs `pre-commit run --all-files`, so a hook that needs uv,'
      ' network access to PyPI, and rewrites files makes every unrelated pull'
      ' request fail. The drift check belongs in'
      ' .github/workflows/constraints-check.yml.'
  )
