# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Guard tests for the published ``constraints-*.txt`` contract.

``README.md`` tells users to install with ``pip install google-adk -c
constraints-<ver>.txt``, so those files must be committed and must stay
readable by ``scripts/update_constraints.sh --check``. These tests pin the
three properties whose absence kept the lint gate permanently red:

* The files exist for every interpreter the script generates.
* Their two-line header is the one the script reconstructs. ``--check`` parses
  ``--exclude-newer`` back out of line 2, so a hand-typed ``uv`` invocation
  would silently make the check date-unstable.
* No ``# -c ...tmp`` annotation leaked in. Passing the committed file to uv via
  ``--constraint`` used to record it as a resolution *source* in every ``# via``
  block, which made the regenerated file permanently differ from the committed
  one.

Plus the direct regression guard: ``pre-commit`` must not shell out to the
network-dependent update script, because the CI lint job runs
``pre-commit run --all-files`` on every pull request.
"""

from __future__ import annotations

from pathlib import Path
import re

import pytest
import yaml

from tests.unittests.test_release_dependencies import _find_pyproject

try:
  import tomllib
except ImportError:
  import tomli as tomllib

_REPO_ROOT = _find_pyproject().parent
_SCRIPT_PATH = _REPO_ROOT / 'scripts' / 'update_constraints.sh'

if not _SCRIPT_PATH.is_file():
  pytest.skip(
      'Not a full source checkout: scripts/update_constraints.sh is absent.',
      allow_module_level=True,
  )


def _parse_python_versions(script: str) -> tuple[str, ...]:
  """Extracts the interpreters from the script's PYTHON_VERSIONS bash array.

  The script is the single source of truth for which constraints files must
  exist. An unparseable array yields an empty tuple, which
  ``test_script_versions_match_python_classifiers`` reports as a failure.
  """
  array = re.findall(r'^PYTHON_VERSIONS=\((.*)\)$', script, re.MULTILINE)
  return tuple(re.findall(r'\d+\.\d+', ' '.join(array)))


_PYTHON_VERSIONS = _parse_python_versions(_SCRIPT_PATH.read_text())

# The two-line header scripts/update_constraints.sh reconstructs verbatim.
_HEADER_LINE_1 = (
    '# This file was autogenerated by uv via the following command:'
)
_HEADER_LINE_2 = (
    r'^#\s+uv pip compile pyproject\.toml --all-extras --python-version {ver}'
    r' --exclude-newer \d{{4}}-\d{{2}}-\d{{2}}'
    r' --index-url https://pypi\.org/simple -o constraints-{ver}\.txt$'
)
# The corruption that --constraint used to inject into every "# via" block.
_LEAKED_ANNOTATION = re.compile(r'^#\s+-c .*\.tmp$', re.MULTILINE)


def _constraints_path(version: str) -> Path:
  return _REPO_ROOT / f'constraints-{version}.txt'


@pytest.mark.parametrize('version', _PYTHON_VERSIONS)
def test_constraints_file_exists_for_every_supported_version(
    version: str,
) -> None:
  path = _constraints_path(version)
  assert path.is_file(), (
      f'{path.name} is missing. README.md documents downloading it, and'
      ' ./scripts/update_constraints.sh --check fails without it.'
  )
  assert path.stat().st_size > 0, f'{path.name} is empty.'


@pytest.mark.parametrize('version', _PYTHON_VERSIONS)
def test_constraints_header_is_script_generated(version: str) -> None:
  path = _constraints_path(version)
  header = path.read_text().splitlines()[:2]

  assert (
      header[0] == _HEADER_LINE_1
  ), f'{path.name} line 1 is not the uv autogeneration banner.'
  assert re.match(_HEADER_LINE_2.format(ver=re.escape(version)), header[1]), (
      f'{path.name} line 2 is not the command'
      ' ./scripts/update_constraints.sh reconstructs, so --check cannot parse'
      f' its --exclude-newer date back out. Got: {header[1]!r}'
  )


@pytest.mark.parametrize('version', _PYTHON_VERSIONS)
def test_constraints_files_have_no_annotation_leakage(version: str) -> None:
  path = _constraints_path(version)
  leaks = _LEAKED_ANNOTATION.findall(path.read_text())
  assert not leaks, (
      f'{path.name} references a temporary constraint file: {leaks}. The'
      ' generator must seed uv with the committed output file, never pass it'
      ' via --constraint.'
  )


def test_script_versions_match_python_classifiers() -> None:
  with _find_pyproject().open('rb') as fh:
    classifiers = tomllib.load(fh)['project']['classifiers']

  classified = {
      c.rsplit('::', 1)[1].strip()
      for c in classifiers
      if c.startswith('Programming Language :: Python :: 3.')
  }
  assert set(_PYTHON_VERSIONS) == classified, (
      'scripts/update_constraints.sh and the pyproject.toml Python'
      ' classifiers disagree on the supported interpreters.'
  )


def test_precommit_does_not_run_constraints_script() -> None:
  config = yaml.safe_load((_REPO_ROOT / '.pre-commit-config.yaml').read_text())

  entries = [
      hook.get('entry', '')
      for repo in config['repos']
      for hook in repo.get('hooks', [])
  ]
  assert not [e for e in entries if 'update_constraints.sh' in e], (
      'The constraints updater is back in .pre-commit-config.yaml. The CI'
      ' lint job runs `pre-commit run --all-files`, so a hook that needs uv,'
      ' network access to PyPI, and rewrites files makes every unrelated pull'
      ' request fail. The drift check belongs in'
      ' .github/workflows/constraints-check.yml.'
  )
